name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint
      run: |
        pylint src/ tests/ --fail-under=8.0

    - name: Run pytest with coverage
      run: |
        pytest --cov=src --cov-report=term-missing --cov-report=xml --cov-fail-under=100

    - name: Upload coverage reports to Codecov
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black

    - name: Check import sorting with isort
      run: |
        # Run isort only on the project package and tests to avoid linting installed editable deps
        isort --check-only --diff src/calculator tests/

    - name: Check code formatting with black
      run: |
        # Run black only on the project package and tests to avoid formatting installed editable deps
        black --check --diff src/calculator tests/

    - name: Run pylint
      run: |
        # Limit pylint to the project package and tests. Adjust the path if your package lives elsewhere under src/.
        pylint src/calculator tests/ --fail-under=8.0